# Configurações do Site
title: PO.B.R.E
email: your-email@example.com
description: >- # Colocar a descrição nas linhas abaixo
  Portal Brasileiro de Romhacking e Emulação
baseurl: ""
url: ""

# Coleções
collections_dir: collections
collections:
  traducoes:
    permalink: "/:collection/:path/"
    output: true


# Configurações de Build
markdown: kramdown
plugins:
  - jekyll-feed

# Ignora os arquivos do sistema
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
