# Configurações do Site
title: PO.B.R.E
email: your-email@example.com
description: >- # Colocar a descrição nas linhas abaixo
  Portal Brasileiro de Romhacking e Emulação
baseurl: "https://hansbonini.com.br/pobre-v2"
url: "https://hansbonini.com.br/pobre-v2"

# Coleções
collections_dir: collections
collections:
  traducoes:
    permalink: "/:collection/:path/"
    output: true

# Configurações de Build
markdown: kramdown
sass:
  style: :compressed
plugins:
  - jekyll-feed

# Ignora os arquivos do sistema
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
